# Pydantic models for API responses
from pydantic import BaseModel, Field
from typing import Any, Optional


class WarningDetail(BaseModel):
    """A single warning attached to a query response."""

    code   : str = Field(..., description="Machine-readable warning code.")
    message: str = Field(..., description="Human-readable warning message.")

    # Warning codes used across the app:
    # AMBIGUOUS_COLUMN    — column name matches multiple tables
    # LOW_CONFIDENCE      — LLM flagged uncertainty in generated SQL
    # LARGE_RESULT        — query may return a very large number of rows
    # MISSING_FILTER      — query has no WHERE clause on a large table
    # FALLBACK_USED       — synonym normalisation or fallback logic triggered


class QueryResponse(BaseModel):
    """Response for POST /query"""

    success      : bool                  = Field(...,  description="True if SQL executed successfully.")
    question     : str                   = Field(...,  description="Original NL question echoed back.")
    generated_sql: Optional[str]         = Field(None, description="SQL generated by the LLM.")
    columns      : list[str]             = Field(default_factory=list, description="Column names from the result.")
    rows         : list[list[Any]]       = Field(default_factory=list, description="Result rows as list of lists.")
    row_count    : int                   = Field(0,    description="Number of rows returned.")
    warnings     : list[WarningDetail]   = Field(default_factory=list, description="Non-fatal warnings.")
    error        : Optional[str]         = Field(None, description="Error message if success=False.")
    session_id   : str                   = Field(...,  description="Session ID echoed back.")


class SchemaTableInfo(BaseModel):
    """Metadata for a single table — used in SchemaResponse."""

    table_name  : str       = Field(..., description="Name of the table.")
    column_count: int       = Field(..., description="Number of columns.")
    columns     : list[str] = Field(..., description="Column names.")
    primary_keys: list[str] = Field(..., description="Primary key column names.")
    foreign_keys: list[str] = Field(..., description="FK descriptions e.g. 'book_id → books.book_id'.")


class SchemaResponse(BaseModel):
    """Response for GET /schema"""

    table_count : int                  = Field(..., description="Total number of tables.")
    tables      : list[SchemaTableInfo]= Field(..., description="Per-table metadata.")
    version     : int                  = Field(..., description="Cache version — increments on schema change.")
    cached_at   : float                = Field(..., description="Unix timestamp of last cache refresh.")
    expires_in  : int                  = Field(..., description="Seconds until cache auto-refreshes.")
    fingerprint : str                  = Field(..., description="MD5 hash of current schema.")


class SessionInfo(BaseModel):
    """Response for GET /session"""

    session_id   : str       = Field(..., description="Session identifier.")
    history_count: int       = Field(..., description="Number of stored query/response pairs.")
    questions    : list[str] = Field(..., description="NL questions asked so far this session.")


class HealthResponse(BaseModel):
    """Response for GET /health"""

    status  : str  = Field(..., description="ok | degraded")
    db      : bool = Field(..., description="True if DB is reachable.")
    cache   : bool = Field(..., description="True if schema is cached.")
    version : str  = Field(..., description="App version string.")